/** Static squad skeleton — fallback until admin enters via paste */
export type WcSquadSeedPlayer = {
  name: string;
  position: string;
  club?: string;
};

export const WC_SQUAD_SEEDS: Record<string, WcSquadSeedPlayer[]> = {
  turkiye: [
    { name: "Uğurcan Çakır", position: "GK", club: "Trabzonspor" },
    { name: "Altay Bayındır", position: "GK", club: "Manchester United" },
    { name: "Mert Günok", position: "GK", club: "Beşiktaş" },
    { name: "Merih Demiral", position: "CB", club: "Al-Ahli" },
    { name: "Abdülkerim Bardakcı", position: "CB", club: "Galatasaray" },
    { name: "Samet Akaydin", position: "CB", club: "Fenerbahçe" },
    { name: "Zeki Çelik", position: "RB", club: "Roma" },
    { name: "Ferdi Kadıoğlu", position: "LB", club: "Brighton" },
    { name: "Orkun Kökçü", position: "CM", club: "Benfica" },
    { name: "Hakan Çalhanoğlu", position: "CM", club: "Inter" },
    { name: "Arda Güler", position: "CAM", club: "Real Madrid" },
    { name: "İrfan Can Kahveci", position: "CAM", club: "Fenerbahçe" },
    { name: "Kenan Yıldız", position: "LW", club: "Juventus" },
    { name: "Barış Alper Yılmaz", position: "LW", club: "Galatasaray" },
    { name: "Kerem Aktürkoğlu", position: "RW", club: "Benfica" },
    { name: "Cengiz Ünder", position: "RW", club: "Fenerbahçe" },
    { name: "Burak Yılmaz", position: "ST", club: "Beşiktaş" },
  ],
  germany: [
    { name: "Manuel Neuer", position: "GK", club: "Bayern" },
    { name: "Marc-André ter Stegen", position: "GK", club: "Barcelona" },
    { name: "Antonio Rüdiger", position: "CB", club: "Real Madrid" },
    { name: "Jonathan Tah", position: "CB", club: "Bayer Leverkusen" },
    { name: "Joshua Kimmich", position: "CDM", club: "Bayern" },
    { name: "Jamal Musiala", position: "CAM", club: "Bayern" },
    { name: "Florian Wirtz", position: "CAM", club: "Bayer Leverkusen" },
    { name: "Leroy Sané", position: "RW", club: "Bayern" },
    { name: "Niclas Füllkrug", position: "ST", club: "Borussia Dortmund" },
    { name: "Harry Kane", position: "ST", club: "Bayern" },
  ],
  brazil: [
    { name: "Alisson", position: "GK", club: "Liverpool" },
    { name: "Marquinhos", position: "CB", club: "PSG" },
    { name: "Gabriel", position: "CB", club: "Arsenal" },
    { name: "Casemiro", position: "CDM", club: "Manchester United" },
    { name: "Rodri", position: "CDM", club: "Manchester City" },
    { name: "Vinícius Júnior", position: "LW", club: "Real Madrid" },
    { name: "Rodrygo", position: "RW", club: "Real Madrid" },
    { name: "Endrick", position: "ST", club: "Real Madrid" },
    { name: "Richarlison", position: "ST", club: "Tottenham" },
  ],
  argentina: [
    { name: "Emiliano Martínez", position: "GK", club: "Aston Villa" },
    { name: "Cristian Romero", position: "CB", club: "Tottenham" },
    { name: "Lisandro Martínez", position: "CB", club: "Manchester United" },
    { name: "Enzo Fernández", position: "CM", club: "Chelsea" },
    { name: "Alexis Mac Allister", position: "CM", club: "Liverpool" },
    { name: "Lionel Messi", position: "RW", club: "Inter Miami" },
    { name: "Ángel Di María", position: "LW", club: "Benfica" },
    { name: "Lautaro Martínez", position: "ST", club: "Inter" },
    { name: "Julián Álvarez", position: "ST", club: "Atlético Madrid" },
  ],
  usa: [
    { name: "Matt Turner", position: "GK", club: "Nottingham Forest" },
    { name: "Sergiño Dest", position: "RB", club: "PSV" },
    { name: "Tyler Adams", position: "CDM", club: "Bournemouth" },
    { name: "Weston McKennie", position: "CM", club: "Juventus" },
    { name: "Christian Pulisic", position: "RW", club: "Milan" },
    { name: "Gio Reyna", position: "CAM", club: "Borussia Dortmund" },
    { name: "Folarin Balogun", position: "ST", club: "Monaco" },
  ],
  france: [
    { name: "Mike Maignan", position: "GK", club: "Milan" },
    { name: "William Saliba", position: "CB", club: "Arsenal" },
    { name: "Dayot Upamecano", position: "CB", club: "Bayern" },
    { name: "Aurélien Tchouaméni", position: "CDM", club: "Real Madrid" },
    { name: "Kylian Mbappé", position: "LW", club: "Real Madrid" },
    { name: "Ousmane Dembélé", position: "RW", club: "PSG" },
    { name: "Olivier Giroud", position: "ST", club: "AC Milan" },
  ],
  england: [
    { name: "Jordan Pickford", position: "GK", club: "Everton" },
    { name: "John Stones", position: "CB", club: "Manchester City" },
    { name: "Declan Rice", position: "CDM", club: "Arsenal" },
    { name: "Jude Bellingham", position: "CM", club: "Real Madrid" },
    { name: "Phil Foden", position: "CAM", club: "Manchester City" },
    { name: "Bukayo Saka", position: "RW", club: "Arsenal" },
    { name: "Harry Kane", position: "ST", club: "Bayern" },
  ],
};
